import = ["/home/ex/.config/alacritty/solar.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Control"

[scrolling]
history = 5000

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 130
lines = 44
